# Big shoutout to my homies at DigitalOcean from which I could base the initial docker setup on
# (https://www.digitalocean.com/community/tutorials/how-to-use-ansible-to-install-and-set-up-docker-on-ubuntu-18-04 but we're debian gang instead)

- name: Postgres Deployment Playbook
  hosts: postgres_target
  vars:
    ansible_python_interpreter: /usr/bin/python3
    # Name of the container, dictates part of the local disk storage path, as well as the Docker container naming
    postgres_container_name: postgres
    # The external port to expose for Postgres
    postgres_external_port: 5432
    # The directory in which to mount the data directory from Postgres
    postgres_data_directory: /etc/postgres-storage/{{ postgres_container_name }}
  tasks:
    - name: Install aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'gnupg-agent', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools' ]

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable
        state: present

    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest

    - name: Install required python modules
      pip:
        name: '{{ item }}'
        loop: [ 'docker', 'jsondiff', 'pyyaml' ]

    - name: Create Postgres database storage directory
      file:
        path: /etc/postgres-storage/{{ postgres_container_name }}
        state: directory
        mode: '0740'

    - name: Create Postgres container stack
      docker_stack:
        state: present
        name: '{{ postgres_container_name }}'
        compose:
        - version: '3'
          services:
            postgres:
              image: "{{ postgres_container_image }}"
              volumes:
                - '{{ postgres_data_directory }}:/var/lib/postgresql/data'
              restart: always
              ports:
                - '{{ postgres_external_port }}:5432'
              environment:
                POSTGRES_DB: '{{ postgres_db }}'
                POSTGRES_USER: '{{ postgres_user }}'
                POSTGRES_PASSWORD: '{{ postgres_password }}'
